language: node_js
node_js:
  - "6"
  - "8"
  - "10"
after_script:
  - nyc report --reporter=text-lcov | coveralls
jobs:
  include:
    - stage: hosting functional test
      if: repo == head_repo OR type == push
      node_js: "6"
      before_script: ./scripts/decrypt-app-credentials.sh
      script: ./scripts/test-hosting.sh
      after_script: skip
    - stage: functions functional test
      if: repo == head_repo OR type == push
      node_js: "8"
      before_script:
        - gcloud version || true
        - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com > __script.sh; bash __script.sh &> /dev/null; fi
        - source /home/travis/google-cloud-sdk/path.bash.inc
        - gcloud version
      script: ./scripts/test-functions-deploy.sh
      after_script: skip
cache:
  directories:
    - "$HOME/google-cloud-sdk/"
    - node_modules
