language: node_js
node_js:
  - "6"
  - "8"
  - "10"
after_script:
  - nyc report --reporter=text-lcov | coveralls
jobs:
  include:
    - stage: hosting functional test
      if: repo == head_repo OR type == push
      node_js: "6"
      before_script: ./scripts/decrypt-app-credentials.sh
      script: ./scripts/test-hosting.sh
      after_script: skip
    - stage: functions functional test
      if: repo == head_repo OR type == push
      node_js: "8"
      before_script: if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
      script: ./scripts/test-functions-deploy.sh
      after_script: skip
cache:
  directories:
    - node_modules
