name: CI Tests

on: 
  - pull_request
  - push

env:
  CI: true
  FIREBASE_EMULATORS_PATH: $GITHUB_WORKSPACE/emulator-cache

jobs:
  unit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: 
          - 8.x
          - 10.x
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: 'Cache npm'
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}

    - run: npm ci
    - run: npm test

  integration:
    needs: unit
    if: github.repository == 'firebase/firebase-tools' && github.event_name == 'push'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 8.x
        script:
          - ./scripts/test-hosting.sh
          - ./scripts/test-triggers-end-to-end.sh 
    steps:
    - name: Check environment
      run: env
    
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 8.x
    
    - name: 'Cache npm'
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}

    - name: 'Cache Emulators'
      uses: actions/cache@v1
      with:
        path: ${{ env.FIREBASE_EMULATORS_PATH }}
        key: ${{ runner.os }}-firebase-emulators-${{ hashFiles('emulator-cache/*.{jar,zip}') }}
      continue-on-error: true

    - run: npm ci
    - run: echo ${{ secrets.service_account_json_base64 }} | base64 -d > ./scripts/service-account.json
    - run: ${{ matrix.script }}
      env:
        COMMIT_SHA: ${{ github.sha }}
        CI_JOB_ID: ${{ job.container.id }}
        FBTOOLS_TARGET_PROJECT: ${{ secrets.FBTOOLS_TARGET_PROJECT }}
    
    - name: Print debug logs
      if: failure()
      run: find . -type f -name "*debug.log" | xargs cat

    - name: 'Show emulators cache'
      run: ls -R $FIREBASE_EMULATORS_PATH
  

