name: Node.js Tests

on: [push]

jobs:
  unit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x, 10.x]
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm test
      env:
        CI: true

  # TODO;
  #  * Only run on 'push' not pull requests
  #  * Share dependency cache
  integration:
    needs: unit
    runs-on: ubuntu-latest
    strategy:
      matrix:
        script: [
          ./scripts/test-hosting.sh, 
          ./scripts/test-triggers-end-to-end.sh
        ]
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 8.x
    - run: npm ci
    - run: echo ${{ secrets.creds_private_json_base64 }} | base64 -d > ./scripts/creds-private.json
    - run: echo ${{ secrets.creds_private_json_base64 }} | base64 -d > ./scripts/creds-public.json
    - run: ${{ matrix.script }}
      env:
        FBTOOLS_TARGET_PROJECT: ${{ secrets.FBTOOLS_TARGET_PROJECT }}
        CI: true
  

