name: Node.js Tests

on: [push]

jobs:
  unit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x, 10.x]
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm test
      env:
        CI: true

  # TODO;
  #  * Only run on 'push' not pull requests
  #  * Decrypt app credentials
  #  * Share dependency cache
  integration:
    needs: unit
    runs-on: ubuntu-latest
    strategy:
      matrix:
        script: [
          ./scripts/test-hosting.sh, 
          ./scripts/test-triggers-end-to-end.sh
        ]
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 8.x
    - run: npm install
    - run: echo "${{ secrets.creds_private_json }}" > ./scripts/creds-private.json
    - run: export GOOGLE_APPLICATION_CREDENTIALS=./scripts/creds-private.json
    - run: ${{ matrix.script }}
      env:
        CI: true
  

