name: Node.js Integration Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        script: [
          ./scripts/test-hosting.sh, 
          ./scripts/test-triggers-end-to-end.sh
        ]
    steps:
    - uses: actions/checkout@v1
    - name: Run ${{ matrix.script }}
      uses: actions/setup-node@v1
      with:
        node-version: 8.x
    - run: npm install
    - run: echo "TODO"
    - run: ${{ matrix.script }}
      env:
        CI: true